### PR TITLE
Fix #179 (dynamic NuGet API endpoints)

### LINKED ISSUE #179: Fix NuGet API
We hardcode the wrong NuGet API endpoint:

Always go to https://api.nuget.org/v3/index.json and get the current RegistrationsBaseUrl.

### PR DESCRIPTION
**Pull request by scovetta**
This change updates the NuGet manager to dynamically find the right endpoint, which should fix some missing packages, as well as minor fixes to a few other files.

### CODE REVIEW

File: src/Shared/PackageManagers/NuGetProjectManager.cs [hunk 1]
```diff
@@ -7,16 +7,66 @@
...
+                        Logger.Warn(ex, "Error parsing NuGet API endpoint: {0}", ex.Message);
+                    }
+                }
+            }
+            catch(Exception ex)
+            {
+                Logger.Warn(ex, "Error parsing NuGet API endpoint: {0}", ex.Message);
+            }
+            RegistrationEndpoint = NUGET_DEFAULT_REGISTRATION_ENDPOINT;
+            return NUGET_DEFAULT_REGISTRATION_ENDPOINT;
```
Comment (jacobmsft) [inline src/Shared/PackageManagers/NuGetProjectManager.cs:69]: shouldn't it be return RegistrationEndpoint;?

Comment (scovetta) [reply src/Shared/PackageManagers/NuGetProjectManager.cs:69]: Shouldn't matter - they're the same value.

Comment (gfs) [reply src/Shared/PackageManagers/NuGetProjectManager.cs:69]: I recommend changing it in case the previous line changes.

File: src/Shared/PackageManagers/NuGetProjectManager.cs [hunk 2]
```diff
@@ -162,11 +306,15 @@ public override Uri GetPackageAbsoluteUri(PackageURL purl)
...
                     if (!string.IsNullOrEmpty(repoCandidate))
                     {
-                        PackageURL repoPurl = GitHubProjectManager.ExtractGitHubPackageURLs(repoCandidate).ToList().FirstOrDefault();
-                        mapping.Add(repoPurl, 1.0F);
-                        return mapping;
+                        var candidate = ExtractGitHubPackageURLs(repoCandidate).FirstOrDefault();
+                        if (candidate != null)
+                        {
+                            mapping.Add((PackageURL)candidate, 1.0F);
+
```
Comment (gfs) [inline src/Shared/PackageManagers/NuGetProjectManager.cs:313]: Whitespace

**Review by gfs — APPROVED** [review]
Broadly LGTM.

File: src/Shared/PackageManagers/NuGetProjectManager.cs (hunk 1 above)
Comment (scovetta) [reply src/Shared/PackageManagers/NuGetProjectManager.cs]: Thanks! Fixed.

File: src/Shared/PackageManagers/NuGetProjectManager.cs (hunk 2 above)
Comment (scovetta) [reply src/Shared/PackageManagers/NuGetProjectManager.cs:313]: @gfs Would `mapping.Add(candidate as PackageURL, 1.0F);` work too? Is there a different because a c-style cast and the `as` operator?

Comment (gfs) [reply src/Shared/PackageManagers/NuGetProjectManager.cs:313]: I think (but haven't tested) that that would work as well if you like how it looks.

Comment (gfs) [reply src/Shared/PackageManagers/NuGetProjectManager.cs:313]: The difference appears to be:

* as operator: failure to cast at runtime returns null. Compile time checks for types. 
* Casting: failure to cast at runtime throws an exception. Compile time checks for types. 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast
